version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/myapp
      - log-data:/myapp/log
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  nginx:
    build:
      context: containers
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: