version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2
    working_directory: ~/tempo
    steps:
      - checkout:
          path: ~/tempo
      - ruby/install-deps:
          bundler-version: 2.2.16

  test:
    docker:
      - image: circleci/ruby:2.6.2
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      DB_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/tempo
    steps:
      - checkout:
          path: ~/tempo
      - ruby/install-deps:
          bundler-version: 2.2.16
      - run:
          name: Database migrate
          command: bin/rails db:migrate
      - run:
          name: test
          command: bin/rails test

  # deploy:
  #   docker:
  #     - image: circleci/ruby:2.6.2
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 19.03.13
  #     - heroku/install
  #     - run:
  #         name: heroku login
  #         command: heroku container:login
  #     - run:
  #         name: push docker image
  #         command: heroku container:push web -a $HEROKU_APP_NAME
  #     - run:
  #         name: release docker image
  #         command: heroku container:release web -a $HEROKU_APP_NAME
  #     - run:
  #         name: database setup
  #         command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build

      # - deploy:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: main
